### ISSUE TITLE
New material you minor icons, colors and contrast issues

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_packages_apps_Dialer#10]
Hi and sorry for bad english.

Latest material you redesign looks good but there are some minor issues with colors.

1. With light theme enabled search bar above dialpad has wrong color.
![Screenshot_20220806-185522_Phone](https://user-images.githubusercontent.com/31875619/183256715-3df08482-c4d4-47e5-9fa1-7a39398cef61.png)
After taping on it the color changes to the correct one
![Screenshot_20220806-185527_Phone](https://user-images.githubusercontent.com/31875619/183256728-83cda2c2-f948-4a7e-a536-18a4b8b90b2f.png)
https://github.com/crdroidandroid/android_packages_apps_Dialer/blob/3082356be8234f4c393d2f7ec42b4ee48ea7238c/java/com/android/dialer/theme/hidden/res/values/colors_dialer_light.xml#L25
I think there should be `system_neutral1_200` or something :-)
Dark theme has no such issue

2. Also search bar has an unnecessary shadow. For example Google Dialer has no shadow around search bar.

3. In this case, this is just my opinion, but I think that in some places the text and icons lack contrast compared to the background. Examples in comparison with google dialer (Up and crDroid Dialer (Down).
![Screenshot_20220806-185555_Phone1](https://user-images.githubusercontent.com/31875619/183257279-f666ff97-2360-4e83-b7f1-32b409261ba5.png)
![Screenshot_20220806-185522_Phone](https://user-images.githubusercontent.com/31875619/183257375-8fd2a011-8ad5-4c71-b929-19e22c146d4b.png)

4. Dialer now has new icons and it's great. Why not use these new microphone and handset icons in search bar and recent ?

5. Incall now has statusbar BLACK background with light and dark theme.
![Screenshot_20220806-193025_Phone](https://user-images.githubusercontent.com/31875619/183257790-833c810b-ea02-4b6c-96a3-ff4850e54fb1.png)
While it looks ok in dark mode, it looks weird in light mode

6. Dialpad page has a shadow (separator?) under statusbar both in light and dark theme.
![Screenshot_20220806-192925_Phone](https://user-images.githubusercontent.com/31875619/183258031-248c2289-aa55-47d0-b735-c13fcd30a08e.png)

7. Dial card and search bar area becomes squared while moving card
![Screenshot_20220806-195629_Телефон](https://user-images.githubusercontent.com/31875619/183258646-52ca2876-fa78-4c32-b2ae-fbd83613a2f6.png)

8. Settings page still has wrong colors at the top and black navbar with light theme
![Screenshot_20220806-202200_Телефон](https://user-images.githubusercontent.com/31875619/183259444-489f151c-acc8-4bf1-b014-a8159e01edc0.png)

P.S.

I would like to express my gratitude to people working on crdroid and especially to neobuddy89 for new dialer design.

This list of minor issues is just my attempt to help a little.
I am not trying to criticize work of the developers

**Comment by neobuddy89** [comment]
Most of these are fixed. 
Contrast issue in bottom nav items can be resolved by choosing right monet color.

**Comment by ghost** [comment]
@neobuddy89 Thank you for your work :+1:  :+1:  :+1:
