### ISSUE TITLE
Duplicated lines in styles.xml

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_packages_apps_Dialer#11]
Hi
lines 54 and 58 are identical
https://github.com/crdroidandroid/android_packages_apps_Dialer/blob/74290f5ae58650ec4c622bd11eede1fa99c96880/java/com/android/dialer/theme/hidden/res/values/styles.xml#L54-L58

**Comment by neobuddy89** [comment]
Removed duplicate line.
