### ISSUE TITLE
Contact images appear in negative shades

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_packages_apps_Dialer#120]
device: vayu
build: 14-09-2024 

Some contact pfps are appearing in negative shades instead of original image.

But it appears correctly on contacts app.

steps to reproduce:
open dialer >> contacts tab >> see contacts with pfps. (not all contacts. it appears randomly)

attached image for reference. ( blurred for privacy)

![Screenshot_20240915-132836_Phone](https://github.com/user-attachments/assets/4aa170ab-0589-474a-906f-015d5a304b44)

![Screenshot_20240915-132836_Phone_cropped](https://github.com/user-attachments/assets/f3c1b69d-7653-4f8a-9fd6-e08bf9ebe3d2)

**Comment by gwolf2u** [comment]
please use issue_tracker
