### ISSUE TITLE
[Feature]Ongoing call chip for AOSP dialer

### ISSUE THREAD

**Issue by shadofficial** [crdroidandroid/android_packages_apps_Dialer#46]
I would like to request a feature which is enabled in the Google Dialer.  It has both Light and Dark version.

![Android-12-Google-Phone-ongoing-call-3](https://user-images.githubusercontent.com/53861418/219361405-7d147192-9126-4b30-b50a-d825f02e2d34.jpg)
![Android-12-Google-Phone-ongoing-call-1](https://user-images.githubusercontent.com/53861418/219361454-3f17a433-a3fe-4675-9206-a7c1a5e72325.jpg)
![Android-12-Google-Phone-ongoing-call-2](https://user-images.githubusercontent.com/53861418/219361467-c89e8cfd-f725-4b50-a4ee-12e081219605.jpg)

**Comment by gwolf2u** [comment]
no plans on that as of now
