### ISSUE TITLE
Request for Material 3 color choices

### ISSUE THREAD

**Issue by Jobatphysics** [crdroidandroid/android_packages_apps_Dialer#49]
Hey devs, First thanks to you all for your hardwork, you are doing a great job. 
I want to request that please make aosp dialer,contact app material 3 colors similar to Google's apps, Google's apps looks great but our crdroid apps looks so much saturated, that's all.
Thanks all

**Comment by gwolf2u** [comment]
we are yet to define perfect colors but we kind of try to stick close to AOSP 
some things may or may not change in the future
