### ISSUE TITLE
Missing merge call button in conference calls

### ISSUE THREAD

**Issue by hajiis** [crdroidandroid/android_packages_apps_Dialer#77]
There is no merge calls button while making conference call
![Screenshot_20230930-113733_Phone](https://github.com/crdroidandroid/android_packages_apps_Dialer/assets/78411669/31696e83-f453-4524-bb3e-e9116b42f810)

**Comment by gwolf2u** [comment]
use issue_tracker

**Comment by hajiis** [comment]
Hi sir, already done that and there is no acknowledgement there.

**Comment by gwolf2u** [comment]
wait for someone to have time to look at
