### ISSUE TITLE
Material you dialer ?

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_packages_apps_Dialer#8]
Hi.

Is it possible to cherry pick some changes from this repo
https://github.com/Octavi-OS/platform_packages_apps_Dialer
To make dialer app looks more modern ?

Now the application looks out of place after massive changes in the design of android

**Comment by ghost** [comment]
I think this man has done some magic. I would like to believe not only in Photoshop.
https://www.behance.net/gallery/143804317/AOSP-Dialer-Redesign-ft-Material-You

~~Unfortunately, I could not find the source code or his git page~~

https://github.com/mukul2259
https://forum.xda-developers.com/m/_undead.4867044/
But there is no dialer anywhere

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_packages_apps_Dialer/commit/3082356be8234f4c393d2f7ec42b4ee48ea7238c

**Comment by ghost** [comment]
Hi.

Can I report minor material you issues right here, or is it better to create a new issue for each issue ?

**Comment by gwolf2u** [comment]
This is closed, so best to report new unless this ticket fix is a regression
